runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 300
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 900
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 300
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 3600
